server:
    port: 8080
logging:
    level:
        root: info
        com.soul: debug
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/soul?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: 123456
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


